### ISSUE TITLE
Decreasing minimal php version to 7.3

### ISSUE THREAD

**Issue by bailey-waystar** [slope-it/clock-mock#33]
I work on a project that is currently using php 7.3. The path to upgrade will involve removing our dependency on timecop. I would like to switch to this library while we are still on php 7.3, so there is less that we will have to manage during our migration. 

I realize I can fork the library and tweak it to my needs, but I would love to remove php 7.4 features and make the library work with php 7.3. Would you be receptive to such a PR?

@asprega

**Comment by asprega** [comment]
Hi Bailey.

I'm sorry but I don't think we should invest development effort to keep compatibility with php versions that are EOL already. If you need to do it I think you should fork the repo.

NOTE: please also consider that you can update to php 7.4 and still use timecop (that's exactly what we did before switching to clock-mock). There is no explicit support, but the extension compiles and works!
