### ISSUE TITLE
Creating new static DateTime objects when frozen doesn't work with IANA timezones

### ISSUE THREAD

**Issue by larbear** [slope-it/clock-mock#37]
The following code will produce an error due to the use of an IANA timezone:

```php
<?php
require "vendor/autoload.php";

SlopeIt\ClockMock\ClockMock::freeze(new DateTime("2023-01-01 05:00:00"));

$dt = "2022-12-25 01:00:00";
$dt = new DateTime($dt, new DateTimeZone("US/Eastern"));
echo $dt->format('Y-m-d H:i:s e') . "\n";
```

The culprit seems to be the constructor, with the following code:

```php
if ($timezone !== null && !$isDateTimeStringRelative) {
    $this->setTimestamp(
        strtotime(
            "$datetime {$timezone->getName()}",
            ClockMock::getFrozenDateTime()->getTimestamp()
        )
    );
}
```

Specifically, `strtotime` will not work with IANA timezones such as US/Eastern.

Looking at the code, it seems like you could return right away if the passed in string isn't relative instead of trying to regenerate the time with `strtotime`:

```php
parent::__construct($datetime, $timezone);

$isDateTimeStringRelative = $this->isRelativeDateString($datetime);

// New code here
if (!$isDateTimeStringRelative) {
    return $this;
}
```

I didn't make a PR as I don't know the system well enough to ensure this works and I couldn't get the PHPUnit tests to work without any changes. Hoping you can take a look at this and check if it's correct or not.

**Comment by asprega** [comment]
Thanks for your report! Just merged a PR that fixes this, fix was released in version 0.3.8.
